### ISSUE TITLE
Deleting last Nota of accord kills program

### ISSUE THREAD

**Issue by ArturKlesun** [ArturKlesun/midiana#79]
By the way, image is not updated when you focus next Nota and delete Nota

Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 0
	at Model.Field.Arr.get(Arr.java:52)
	at BlockSpacePkg.StaffPkg.Accord.Accord.getFocusedNota(Accord.java:134)
	at BlockSpacePkg.StaffPkg.Accord.Accord.getFocusedChild(Accord.java:175)
	at BlockSpacePkg.StaffPkg.Accord.Accord.getFocusedChild(Accord.java:18)
	at Main.MajesticWindow.updateMenuBar(MajesticWindow.java:156)
	at Model.AbstractHandler.handleKey(AbstractHandler.java:70)
	at Model.AbstractHandler.handleKey(AbstractHandler.java:60)
	at Model.AbstractHandler.handleKey(AbstractHandler.java:60)
	at Model.AbstractHandler.handleKey(AbstractHandler.java:60)
	at Model.AbstractHandler.handleKey(AbstractHandler.java:60)
	at Model.AbstractHandler.handleKey(AbstractHandler.java:60)
	at Model.AbstractHandler.keyPressed(AbstractHandler.java:39)
	at java.awt.Component.processKeyEvent(Component.java:6483)
	at javax.swing.JComponent.processKeyEvent(JComponent.java:2832)
	at java.awt.Component.processEvent(Component.java:6302)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
	at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:806)
	at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1074)
	at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:945)
	at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:771)
	at java.awt.Component.dispatchEventImpl(Component.java:4752)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by ArturKlesun** [comment]
kinda resolved
